#!/usr/bin/env python3
"""Generate global / individual / mixed CPMG datasets + configs for validation.

Each scenario has 5 residues at 2 fields, ground-truth generated by the exact
Matrix model with a strong minor state (pB=0.1 -> large Rex -> well-determined
kex).  Ground truth is written to <scenario>/truth.json for evaluation.

  global      : all 5 residues share kex=1000        -> expect global preferred
  individual  : each residue own kex (400..2500)      -> expect individual preferred
  mixed       : 4 share kex=1000, 1 outlier (R5=2500) -> expect outlier flagged,
                global restored after removing it

Run via demo/run_demo.sh, or directly:
    python demo/make_scenarios.py
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)
from cpmg.model_2state import CPMG_model

np.random.seed(1234)

FIELDS = [60.12, 90.23]
R20_FC = [0.0, 2.0]          # per-field R2_0 offset
TCP = 0.04
VCPMG = np.array([50., 100., 200., 300., 400., 500., 600., 700., 800., 900., 1000.])
NOISE = 0.01                 # 1% noise -> tight fits
R2_0 = 20.0
CSD = [2.0, 2.4, 2.8, 3.2, 3.6]   # ppm, per residue (strong dispersion)
NAMES = ['R1', 'R2', 'R3', 'R4', 'R5']
PB = 0.1                     # minor-state population (strong exchange)

SCENARIOS = {
    'global':     [1000, 1000, 1000, 1000, 1000],
    'individual': [400,  700,  1000, 1500, 2500],
    # majority consensus (kex=1000) + one clear outlier (R5) -> clean split
    'mixed':      [1000, 1000, 1000, 1000, 2500],
}

m = CPMG_model()


def gen_scenario(name, kex_list, outdir):
    os.makedirs(outdir, exist_ok=True)
    truth = {'name': name, 'residues': [
        {'name': n, 'kex': k, 'pB': PB, 'csd': c}
        for n, k, c in zip(NAMES, kex_list, CSD)]}

    datasets = []
    for fi, field in enumerate(FIELDS):
        buff = '%5.2f\n%f\n#nu_cpmg(Hz)  R2(1/s)  Esd(R2)\n' % (field, TCP)
        for rname, kex, csd in zip(NAMES, kex_list, CSD):
            kAB = PB * kex
            kBA = (1.0 - PB) * kex
            buff += '# %s\n' % rname
            for v in VCPMG:
                domega = csd * 2 * np.pi * field
                r2_0 = R2_0 + R20_FC[fi]
                ideal = m.R2_clc_matrix(kAB, kBA, domega, r2_0, v, TCP)
                std = ideal * NOISE
                obs = std * np.random.randn() + ideal
                buff += '%8.3f %8.3f %8.3f\n' % (v, obs, std)
        path = os.path.join(outdir, 'f%d.dat' % int(field))
        with open(path, 'w') as fh:
            fh.write(buff)
        datasets.append(os.path.basename(path))

    conf = {
        'Project Name': name,
        'comments': 'scenario: %s' % name,
        'datasets': datasets,
        'exchange': 'slow',          # report kAB/kBA/csd directly (no phi)
        'model': 'Matrix',           # exact model matches the generator
        'init': {'mode': 'values', 'kex': 1000.0, 'pB': PB, 'csd': 2.5},
        'compare_aic': True,
        'jackknife': True,
        'residues': [{'name': n, 'flag': 'on'} for n in NAMES],
    }
    with open(os.path.join(outdir, '%s.conf' % name), 'w') as fh:
        json.dump(conf, fh, indent=4)

    # mixed also gets a "recovery" config with the outlier R5 deactivated,
    # to show a clean global fit is restored once the outlier is removed.
    if name == 'mixed':
        rec = json.loads(json.dumps(conf))
        rec['Project Name'] = 'mixed-recover'
        for r in rec['residues']:
            if r['name'] == 'R5':
                r['flag'] = 'off'
        with open(os.path.join(outdir, 'mixed-recover.conf'), 'w') as fh:
            json.dump(rec, fh, indent=4)

    with open(os.path.join(outdir, 'truth.json'), 'w') as fh:
        json.dump(truth, fh, indent=4)
    print('generated %-11s -> %s' % (name, os.path.relpath(outdir, REPO)))


if __name__ == '__main__':
    for name, kex_list in SCENARIOS.items():
        gen_scenario(name, kex_list, os.path.join(HERE, name))
    print('done.')
